In [9]:
#import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [10]:
#load iris dataset
from sklearn.datasets import load_iris
iris=load_iris()


In [11]:
#preprocessing the dataset
X=iris.data
y=iris.target


In [12]:
#split the dataset into train and test data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)


In [13]:
#to train the model
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [14]:
#make prediction on test data
y_pred=knn.predict(X_test)


In [15]:
#compare the accuracy between the predicted and the actual output y_test
from sklearn import metrics
print("accuracy=",metrics.accuracy_score(y_pred,y_test))
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

accuracy= 0.9666666666666667
[[ 5  0  0]
 [ 0 13  1]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       1.00      0.93      0.96        14
           2       0.92      1.00      0.96        11

   micro avg       0.97      0.97      0.97        30
   macro avg       0.97      0.98      0.97        30
weighted avg       0.97      0.97      0.97        30

